### ISSUE TITLE
Smartphone Ai skill

### ISSUE THREAD

**Issue by spogy10** [sultanofcardio/curfewja#3]
Would be cool if this could be incorporated into the Google assistant so I can ask my phone when curfew is. I might try that

**Comment by sultanofcardio** [comment]
Sounds like a cool idea, thanks for suggesting it. I encourage you to try it. Feel free to use any of the code in this repo or the data provided at https://curfewja.com/data.json

That's not something I will be doing in this repo though, so I'll have to close this issue.
